version: 2.1

jobs:
  create-and-upload-package:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install twine"
          command: "pip3.12 install twine"

workflows:
  say-hello-workflow:
    jobs:
      - create-and-upload-package