version: 2.1

orbs:
  python: circleci/python@3.3.0

jobs:
  publish:
    executor: python/default
    steps:
      - checkout
      - run: pip install twine && python3 setup.py bdist_wheel && twine upload dist/*

workflows:
  publish-workflow:
    jobs:
      - publish